# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\MyCode\FAEPro\FAEPro\GUI\FeatureExtraction.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FeatureExtraction(object):
    def setupUi(self, FeatureExtraction):
        FeatureExtraction.setObjectName("FeatureExtraction")
        FeatureExtraction.resize(1025, 820)
        self.gridLayout = QtWidgets.QGridLayout(FeatureExtraction)
        self.gridLayout.setObjectName("gridLayout")
        self.plainTextEditOutput = QtWidgets.QPlainTextEdit(FeatureExtraction)
        self.plainTextEditOutput.setObjectName("plainTextEditOutput")
        self.gridLayout.addWidget(self.plainTextEditOutput, 0, 1, 1, 3)
        self.label_5 = QtWidgets.QLabel(FeatureExtraction)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 1, 1, 2)
        self.buttonGo = QtWidgets.QPushButton(FeatureExtraction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonGo.sizePolicy().hasHeightForWidth())
        self.buttonGo.setSizePolicy(sizePolicy)
        self.buttonGo.setMinimumSize(QtCore.QSize(0, 30))
        self.buttonGo.setObjectName("buttonGo")
        self.gridLayout.addWidget(self.buttonGo, 2, 1, 1, 3)
        self.progressBarTotal = QtWidgets.QProgressBar(FeatureExtraction)
        self.progressBarTotal.setProperty("value", 24)
        self.progressBarTotal.setObjectName("progressBarTotal")
        self.gridLayout.addWidget(self.progressBarTotal, 1, 3, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listWidgetImageFiles = QtWidgets.QListWidget(FeatureExtraction)
        self.listWidgetImageFiles.setMaximumSize(QtCore.QSize(16777215, 90))
        self.listWidgetImageFiles.setObjectName("listWidgetImageFiles")
        self.gridLayout_2.addWidget(self.listWidgetImageFiles, 6, 0, 1, 1)
        self.frame = QtWidgets.QFrame(FeatureExtraction)
        self.frame.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2.addWidget(self.frame, 1, 0, 1, 2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEditFileName = QtWidgets.QLineEdit(FeatureExtraction)
        self.lineEditFileName.setObjectName("lineEditFileName")
        self.horizontalLayout_3.addWidget(self.lineEditFileName)
        self.buttonAdd = QtWidgets.QPushButton(FeatureExtraction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonAdd.sizePolicy().hasHeightForWidth())
        self.buttonAdd.setSizePolicy(sizePolicy)
        self.buttonAdd.setMinimumSize(QtCore.QSize(0, 30))
        self.buttonAdd.setObjectName("buttonAdd")
        self.horizontalLayout_3.addWidget(self.buttonAdd)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.buttonBrowseFile = QtWidgets.QPushButton(FeatureExtraction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBrowseFile.sizePolicy().hasHeightForWidth())
        self.buttonBrowseFile.setSizePolicy(sizePolicy)
        self.buttonBrowseFile.setMinimumSize(QtCore.QSize(0, 30))
        self.buttonBrowseFile.setObjectName("buttonBrowseFile")
        self.verticalLayout_3.addWidget(self.buttonBrowseFile)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 6, 1, 1, 1)
        self.labelImageFilePatterns = QtWidgets.QLabel(FeatureExtraction)
        self.labelImageFilePatterns.setObjectName("labelImageFilePatterns")
        self.gridLayout_2.addWidget(self.labelImageFilePatterns, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(FeatureExtraction)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelSource = QtWidgets.QLabel(FeatureExtraction)
        self.labelSource.setObjectName("labelSource")
        self.horizontalLayout.addWidget(self.labelSource)
        self.lineEditSource = QtWidgets.QLineEdit(FeatureExtraction)
        self.lineEditSource.setObjectName("lineEditSource")
        self.horizontalLayout.addWidget(self.lineEditSource)
        self.buttonBrowseSourceFolder = QtWidgets.QPushButton(FeatureExtraction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBrowseSourceFolder.sizePolicy().hasHeightForWidth())
        self.buttonBrowseSourceFolder.setSizePolicy(sizePolicy)
        self.buttonBrowseSourceFolder.setMinimumSize(QtCore.QSize(0, 30))
        self.buttonBrowseSourceFolder.setObjectName("buttonBrowseSourceFolder")
        self.horizontalLayout.addWidget(self.buttonBrowseSourceFolder)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelSource_2 = QtWidgets.QLabel(FeatureExtraction)
        self.labelSource_2.setObjectName("labelSource_2")
        self.horizontalLayout_2.addWidget(self.labelSource_2)
        self.lineEditRoiFileName = QtWidgets.QLineEdit(FeatureExtraction)
        self.lineEditRoiFileName.setObjectName("lineEditRoiFileName")
        self.horizontalLayout_2.addWidget(self.lineEditRoiFileName)
        self.buttonBrowseRoiFile = QtWidgets.QPushButton(FeatureExtraction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBrowseRoiFile.sizePolicy().hasHeightForWidth())
        self.buttonBrowseRoiFile.setSizePolicy(sizePolicy)
        self.buttonBrowseRoiFile.setMinimumSize(QtCore.QSize(0, 30))
        self.buttonBrowseRoiFile.setObjectName("buttonBrowseRoiFile")
        self.horizontalLayout_2.addWidget(self.buttonBrowseRoiFile)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelOutputFile = QtWidgets.QLabel(FeatureExtraction)
        self.labelOutputFile.setObjectName("labelOutputFile")
        self.horizontalLayout_5.addWidget(self.labelOutputFile)
        self.lineEditOutputFile = QtWidgets.QLineEdit(FeatureExtraction)
        self.lineEditOutputFile.setObjectName("lineEditOutputFile")
        self.horizontalLayout_5.addWidget(self.lineEditOutputFile)
        self.buttonBrowseOutputFile = QtWidgets.QPushButton(FeatureExtraction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBrowseOutputFile.sizePolicy().hasHeightForWidth())
        self.buttonBrowseOutputFile.setSizePolicy(sizePolicy)
        self.buttonBrowseOutputFile.setMinimumSize(QtCore.QSize(0, 30))
        self.buttonBrowseOutputFile.setObjectName("buttonBrowseOutputFile")
        self.horizontalLayout_5.addWidget(self.buttonBrowseOutputFile)
        self.labelOutputFile_3 = QtWidgets.QLabel(FeatureExtraction)
        self.labelOutputFile_3.setObjectName("labelOutputFile_3")
        self.horizontalLayout_5.addWidget(self.labelOutputFile_3)
        self.lineEditFeaturePrefix = QtWidgets.QLineEdit(FeatureExtraction)
        self.lineEditFeaturePrefix.setObjectName("lineEditFeaturePrefix")
        self.horizontalLayout_5.addWidget(self.lineEditFeaturePrefix)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.labelOutputFile_2 = QtWidgets.QLabel(FeatureExtraction)
        self.labelOutputFile_2.setObjectName("labelOutputFile_2")
        self.verticalLayout_5.addWidget(self.labelOutputFile_2)
        self.frame_6 = QtWidgets.QFrame(FeatureExtraction)
        self.frame_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5.addWidget(self.frame_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(FeatureExtraction)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.frame_2 = QtWidgets.QFrame(FeatureExtraction)
        self.frame_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout.addWidget(self.frame_2)
        self.checkBoxOriginal = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxOriginal.setObjectName("checkBoxOriginal")
        self.verticalLayout.addWidget(self.checkBoxOriginal)
        self.checkBoxWavelet = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxWavelet.setObjectName("checkBoxWavelet")
        self.verticalLayout.addWidget(self.checkBoxWavelet)
        self.checkBoxSquare = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxSquare.setObjectName("checkBoxSquare")
        self.verticalLayout.addWidget(self.checkBoxSquare)
        self.checkBoxSquareRoot = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxSquareRoot.setObjectName("checkBoxSquareRoot")
        self.verticalLayout.addWidget(self.checkBoxSquareRoot)
        self.checkBoxLoG = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxLoG.setObjectName("checkBoxLoG")
        self.verticalLayout.addWidget(self.checkBoxLoG)
        self.checkBoxLogarithm = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxLogarithm.setObjectName("checkBoxLogarithm")
        self.verticalLayout.addWidget(self.checkBoxLogarithm)
        self.checkBoxExponential = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxExponential.setObjectName("checkBoxExponential")
        self.verticalLayout.addWidget(self.checkBoxExponential)
        self.checkBoxGradient = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxGradient.setObjectName("checkBoxGradient")
        self.verticalLayout.addWidget(self.checkBoxGradient)
        self.checkBoxLocalBinaryPattern2D = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxLocalBinaryPattern2D.setObjectName("checkBoxLocalBinaryPattern2D")
        self.verticalLayout.addWidget(self.checkBoxLocalBinaryPattern2D)
        self.checkBoxLocalBinaryPattern3D = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxLocalBinaryPattern3D.setObjectName("checkBoxLocalBinaryPattern3D")
        self.verticalLayout.addWidget(self.checkBoxLocalBinaryPattern3D)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(FeatureExtraction)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.frame_3 = QtWidgets.QFrame(FeatureExtraction)
        self.frame_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2.addWidget(self.frame_3)
        self.checkBoxFirstOrderStatistics = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxFirstOrderStatistics.setObjectName("checkBoxFirstOrderStatistics")
        self.verticalLayout_2.addWidget(self.checkBoxFirstOrderStatistics)
        self.checkBoxShapeBased2D = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxShapeBased2D.setObjectName("checkBoxShapeBased2D")
        self.verticalLayout_2.addWidget(self.checkBoxShapeBased2D)
        self.checkBoxGLCM = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxGLCM.setObjectName("checkBoxGLCM")
        self.verticalLayout_2.addWidget(self.checkBoxGLCM)
        self.checkBoxGLRLM = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxGLRLM.setObjectName("checkBoxGLRLM")
        self.verticalLayout_2.addWidget(self.checkBoxGLRLM)
        self.checkBoxGLSZM = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxGLSZM.setObjectName("checkBoxGLSZM")
        self.verticalLayout_2.addWidget(self.checkBoxGLSZM)
        self.checkBoxGLDM = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxGLDM.setObjectName("checkBoxGLDM")
        self.verticalLayout_2.addWidget(self.checkBoxGLDM)
        self.checkBoxNGTDM = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxNGTDM.setObjectName("checkBoxNGTDM")
        self.verticalLayout_2.addWidget(self.checkBoxNGTDM)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 0, 3, 1)

        self.retranslateUi(FeatureExtraction)
        QtCore.QMetaObject.connectSlotsByName(FeatureExtraction)

    def retranslateUi(self, FeatureExtraction):
        _translate = QtCore.QCoreApplication.translate
        FeatureExtraction.setWindowTitle(_translate("FeatureExtraction", "Form"))
        self.label_5.setText(_translate("FeatureExtraction", "Total: "))
        self.buttonGo.setText(_translate("FeatureExtraction", "Go!"))
        self.buttonAdd.setText(_translate("FeatureExtraction", "Add"))
        self.buttonBrowseFile.setText(_translate("FeatureExtraction", "Browse..."))
        self.labelImageFilePatterns.setText(_translate("FeatureExtraction", "Image File Patterns:"))
        self.label.setText(_translate("FeatureExtraction", "Files"))
        self.labelSource.setText(_translate("FeatureExtraction", "Source Folder: "))
        self.buttonBrowseSourceFolder.setText(_translate("FeatureExtraction", "Browse..."))
        self.labelSource_2.setText(_translate("FeatureExtraction", "ROI File Name:"))
        self.buttonBrowseRoiFile.setText(_translate("FeatureExtraction", "Browse..."))
        self.labelOutputFile.setText(_translate("FeatureExtraction", "Output:"))
        self.lineEditOutputFile.setToolTip(_translate("FeatureExtraction", "Path to output feature matrix file."))
        self.buttonBrowseOutputFile.setText(_translate("FeatureExtraction", "Browse..."))
        self.labelOutputFile_3.setText(_translate("FeatureExtraction", "Feature Prefix:"))
        self.lineEditFeaturePrefix.setToolTip(_translate("FeatureExtraction", "Path to output feature matrix file."))
        self.labelOutputFile_2.setText(_translate("FeatureExtraction", "Options"))
        self.label_2.setText(_translate("FeatureExtraction", "Image Types"))
        self.checkBoxOriginal.setText(_translate("FeatureExtraction", "Original"))
        self.checkBoxWavelet.setText(_translate("FeatureExtraction", "Wavelet Transform"))
        self.checkBoxSquare.setText(_translate("FeatureExtraction", "Square"))
        self.checkBoxSquareRoot.setText(_translate("FeatureExtraction", "Square Root"))
        self.checkBoxLoG.setText(_translate("FeatureExtraction", "Laplacian of Gaussian"))
        self.checkBoxLogarithm.setText(_translate("FeatureExtraction", "Logarithm"))
        self.checkBoxExponential.setText(_translate("FeatureExtraction", "Exponential"))
        self.checkBoxGradient.setText(_translate("FeatureExtraction", "Gradient"))
        self.checkBoxLocalBinaryPattern2D.setText(_translate("FeatureExtraction", "Local Binary Pattern (2D)"))
        self.checkBoxLocalBinaryPattern3D.setText(_translate("FeatureExtraction", "Local Binary Pattern (3D)"))
        self.label_3.setText(_translate("FeatureExtraction", "Feature Categories"))
        self.checkBoxFirstOrderStatistics.setText(_translate("FeatureExtraction", "First Order Statistics"))
        self.checkBoxShapeBased2D.setText(_translate("FeatureExtraction", "Shape-based"))
        self.checkBoxGLCM.setToolTip(_translate("FeatureExtraction", "Gray Level Cooccurence Matrix"))
        self.checkBoxGLCM.setText(_translate("FeatureExtraction", "GLCM"))
        self.checkBoxGLRLM.setToolTip(_translate("FeatureExtraction", "Gray Level Run Length Matrix"))
        self.checkBoxGLRLM.setText(_translate("FeatureExtraction", "GLRLM"))
        self.checkBoxGLSZM.setToolTip(_translate("FeatureExtraction", "Gray Level Size Zone Matrix"))
        self.checkBoxGLSZM.setText(_translate("FeatureExtraction", "GLSZM"))
        self.checkBoxGLDM.setToolTip(_translate("FeatureExtraction", "Gray Level Dependence Matrix"))
        self.checkBoxGLDM.setText(_translate("FeatureExtraction", "GLDM"))
        self.checkBoxNGTDM.setToolTip(_translate("FeatureExtraction", "Neigboring Gray Tone Difference Matrix"))
        self.checkBoxNGTDM.setText(_translate("FeatureExtraction", "NGTDM"))

