# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\MyCode\FeatureAnalysisPro\GUI\FeatureExtraction2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FeatureExtraction(object):
    def setupUi(self, FeatureExtraction):
        FeatureExtraction.setObjectName("FeatureExtraction")
        FeatureExtraction.resize(1221, 479)
        self.gridLayout_3 = QtWidgets.QGridLayout(FeatureExtraction)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelSource = QtWidgets.QLabel(FeatureExtraction)
        self.labelSource.setObjectName("labelSource")
        self.horizontalLayout_2.addWidget(self.labelSource)
        self.lineEditSourceFolder = QtWidgets.QLineEdit(FeatureExtraction)
        self.lineEditSourceFolder.setObjectName("lineEditSourceFolder")
        self.horizontalLayout_2.addWidget(self.lineEditSourceFolder)
        self.buttonBrowseSourceFolder = QtWidgets.QPushButton(FeatureExtraction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBrowseSourceFolder.sizePolicy().hasHeightForWidth())
        self.buttonBrowseSourceFolder.setSizePolicy(sizePolicy)
        self.buttonBrowseSourceFolder.setMinimumSize(QtCore.QSize(0, 30))
        self.buttonBrowseSourceFolder.setObjectName("buttonBrowseSourceFolder")
        self.horizontalLayout_2.addWidget(self.buttonBrowseSourceFolder)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelImageFilePatterns = QtWidgets.QLabel(FeatureExtraction)
        self.labelImageFilePatterns.setObjectName("labelImageFilePatterns")
        self.gridLayout_2.addWidget(self.labelImageFilePatterns, 0, 0, 1, 2)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditkeyShowName = QtWidgets.QLineEdit(FeatureExtraction)
        self.lineEditkeyShowName.setObjectName("lineEditkeyShowName")
        self.gridLayout.addWidget(self.lineEditkeyShowName, 3, 1, 1, 1)
        self.labelImageFilePatterns_2 = QtWidgets.QLabel(FeatureExtraction)
        self.labelImageFilePatterns_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelImageFilePatterns_2.setObjectName("labelImageFilePatterns_2")
        self.gridLayout.addWidget(self.labelImageFilePatterns_2, 1, 0, 1, 1)
        self.lineEditkeyExclude = QtWidgets.QLineEdit(FeatureExtraction)
        self.lineEditkeyExclude.setObjectName("lineEditkeyExclude")
        self.gridLayout.addWidget(self.lineEditkeyExclude, 2, 1, 1, 1)
        self.lineEditkeyInclude = QtWidgets.QLineEdit(FeatureExtraction)
        self.lineEditkeyInclude.setObjectName("lineEditkeyInclude")
        self.gridLayout.addWidget(self.lineEditkeyInclude, 1, 1, 1, 1)
        self.labelImageFilePatterns_4 = QtWidgets.QLabel(FeatureExtraction)
        self.labelImageFilePatterns_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelImageFilePatterns_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelImageFilePatterns_4.setObjectName("labelImageFilePatterns_4")
        self.gridLayout.addWidget(self.labelImageFilePatterns_4, 3, 0, 1, 1)
        self.labelImageFilePatterns_3 = QtWidgets.QLabel(FeatureExtraction)
        self.labelImageFilePatterns_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelImageFilePatterns_3.setObjectName("labelImageFilePatterns_3")
        self.gridLayout.addWidget(self.labelImageFilePatterns_3, 2, 0, 1, 1)
        self.radioImagePattern = QtWidgets.QRadioButton(FeatureExtraction)
        self.radioImagePattern.setChecked(True)
        self.radioImagePattern.setObjectName("radioImagePattern")
        self.gridLayout.addWidget(self.radioImagePattern, 0, 0, 1, 1)
        self.radioRoiPattern = QtWidgets.QRadioButton(FeatureExtraction)
        self.radioRoiPattern.setObjectName("radioRoiPattern")
        self.gridLayout.addWidget(self.radioRoiPattern, 0, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.buttonAddOne = QtWidgets.QPushButton(FeatureExtraction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonAddOne.sizePolicy().hasHeightForWidth())
        self.buttonAddOne.setSizePolicy(sizePolicy)
        self.buttonAddOne.setMinimumSize(QtCore.QSize(0, 30))
        self.buttonAddOne.setObjectName("buttonAddOne")
        self.verticalLayout.addWidget(self.buttonAddOne)
        self.buttonRemoveOne = QtWidgets.QPushButton(FeatureExtraction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonRemoveOne.sizePolicy().hasHeightForWidth())
        self.buttonRemoveOne.setSizePolicy(sizePolicy)
        self.buttonRemoveOne.setMinimumSize(QtCore.QSize(0, 30))
        self.buttonRemoveOne.setObjectName("buttonRemoveOne")
        self.verticalLayout.addWidget(self.buttonRemoveOne)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.tableFilePattern = QtWidgets.QTableWidget(FeatureExtraction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableFilePattern.sizePolicy().hasHeightForWidth())
        self.tableFilePattern.setSizePolicy(sizePolicy)
        self.tableFilePattern.setMinimumSize(QtCore.QSize(450, 0))
        self.tableFilePattern.setMaximumSize(QtCore.QSize(500, 16777215))
        self.tableFilePattern.setObjectName("tableFilePattern")
        self.tableFilePattern.setColumnCount(0)
        self.tableFilePattern.setRowCount(0)
        self.horizontalLayout.addWidget(self.tableFilePattern)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_8.addLayout(self.verticalLayout_2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_3 = QtWidgets.QFrame(FeatureExtraction)
        self.frame_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5.addWidget(self.frame_3)
        self.labelSource_2 = QtWidgets.QLabel(FeatureExtraction)
        self.labelSource_2.setObjectName("labelSource_2")
        self.verticalLayout_5.addWidget(self.labelSource_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(FeatureExtraction)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.checkBoxOriginal = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxOriginal.setChecked(True)
        self.checkBoxOriginal.setObjectName("checkBoxOriginal")
        self.verticalLayout_4.addWidget(self.checkBoxOriginal)
        self.checkBoxWavelet = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxWavelet.setObjectName("checkBoxWavelet")
        self.verticalLayout_4.addWidget(self.checkBoxWavelet)
        self.checkBoxSquare = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxSquare.setObjectName("checkBoxSquare")
        self.verticalLayout_4.addWidget(self.checkBoxSquare)
        self.checkBoxSquareRoot = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxSquareRoot.setObjectName("checkBoxSquareRoot")
        self.verticalLayout_4.addWidget(self.checkBoxSquareRoot)
        self.checkBoxLoG = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxLoG.setObjectName("checkBoxLoG")
        self.verticalLayout_4.addWidget(self.checkBoxLoG)
        self.checkBoxLogarithm = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxLogarithm.setObjectName("checkBoxLogarithm")
        self.verticalLayout_4.addWidget(self.checkBoxLogarithm)
        self.checkBoxExponential = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxExponential.setObjectName("checkBoxExponential")
        self.verticalLayout_4.addWidget(self.checkBoxExponential)
        self.checkBoxGradient = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxGradient.setObjectName("checkBoxGradient")
        self.verticalLayout_4.addWidget(self.checkBoxGradient)
        self.checkBoxLocalBinaryPattern2D = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxLocalBinaryPattern2D.setObjectName("checkBoxLocalBinaryPattern2D")
        self.verticalLayout_4.addWidget(self.checkBoxLocalBinaryPattern2D)
        self.checkBoxLocalBinaryPattern3D = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxLocalBinaryPattern3D.setObjectName("checkBoxLocalBinaryPattern3D")
        self.verticalLayout_4.addWidget(self.checkBoxLocalBinaryPattern3D)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(FeatureExtraction)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.checkBoxFirstOrderStatistics = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxFirstOrderStatistics.setChecked(True)
        self.checkBoxFirstOrderStatistics.setObjectName("checkBoxFirstOrderStatistics")
        self.verticalLayout_3.addWidget(self.checkBoxFirstOrderStatistics)
        self.checkBoxShapeBased2D = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxShapeBased2D.setChecked(True)
        self.checkBoxShapeBased2D.setObjectName("checkBoxShapeBased2D")
        self.verticalLayout_3.addWidget(self.checkBoxShapeBased2D)
        self.checkBoxGLCM = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxGLCM.setChecked(True)
        self.checkBoxGLCM.setObjectName("checkBoxGLCM")
        self.verticalLayout_3.addWidget(self.checkBoxGLCM)
        self.checkBoxGLRLM = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxGLRLM.setObjectName("checkBoxGLRLM")
        self.verticalLayout_3.addWidget(self.checkBoxGLRLM)
        self.checkBoxGLSZM = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxGLSZM.setObjectName("checkBoxGLSZM")
        self.verticalLayout_3.addWidget(self.checkBoxGLSZM)
        self.checkBoxGLDM = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxGLDM.setObjectName("checkBoxGLDM")
        self.verticalLayout_3.addWidget(self.checkBoxGLDM)
        self.checkBoxNGTDM = QtWidgets.QCheckBox(FeatureExtraction)
        self.checkBoxNGTDM.setObjectName("checkBoxNGTDM")
        self.verticalLayout_3.addWidget(self.checkBoxNGTDM)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.plainTextOutput = QtWidgets.QPlainTextEdit(FeatureExtraction)
        self.plainTextOutput.setMinimumSize(QtCore.QSize(400, 0))
        self.plainTextOutput.setObjectName("plainTextOutput")
        self.verticalLayout_6.addWidget(self.plainTextOutput)
        self.buttonRun = QtWidgets.QPushButton(FeatureExtraction)
        self.buttonRun.setObjectName("buttonRun")
        self.verticalLayout_6.addWidget(self.buttonRun)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)

        self.retranslateUi(FeatureExtraction)
        QtCore.QMetaObject.connectSlotsByName(FeatureExtraction)
        FeatureExtraction.setTabOrder(self.lineEditSourceFolder, self.buttonBrowseSourceFolder)
        FeatureExtraction.setTabOrder(self.buttonBrowseSourceFolder, self.lineEditkeyInclude)
        FeatureExtraction.setTabOrder(self.lineEditkeyInclude, self.lineEditkeyExclude)
        FeatureExtraction.setTabOrder(self.lineEditkeyExclude, self.lineEditkeyShowName)
        FeatureExtraction.setTabOrder(self.lineEditkeyShowName, self.radioImagePattern)
        FeatureExtraction.setTabOrder(self.radioImagePattern, self.radioRoiPattern)
        FeatureExtraction.setTabOrder(self.radioRoiPattern, self.buttonAddOne)
        FeatureExtraction.setTabOrder(self.buttonAddOne, self.buttonRemoveOne)
        FeatureExtraction.setTabOrder(self.buttonRemoveOne, self.tableFilePattern)
        FeatureExtraction.setTabOrder(self.tableFilePattern, self.checkBoxOriginal)
        FeatureExtraction.setTabOrder(self.checkBoxOriginal, self.checkBoxWavelet)
        FeatureExtraction.setTabOrder(self.checkBoxWavelet, self.checkBoxSquare)
        FeatureExtraction.setTabOrder(self.checkBoxSquare, self.checkBoxSquareRoot)
        FeatureExtraction.setTabOrder(self.checkBoxSquareRoot, self.checkBoxLoG)
        FeatureExtraction.setTabOrder(self.checkBoxLoG, self.checkBoxLogarithm)
        FeatureExtraction.setTabOrder(self.checkBoxLogarithm, self.checkBoxExponential)
        FeatureExtraction.setTabOrder(self.checkBoxExponential, self.checkBoxGradient)
        FeatureExtraction.setTabOrder(self.checkBoxGradient, self.checkBoxLocalBinaryPattern2D)
        FeatureExtraction.setTabOrder(self.checkBoxLocalBinaryPattern2D, self.checkBoxLocalBinaryPattern3D)
        FeatureExtraction.setTabOrder(self.checkBoxLocalBinaryPattern3D, self.checkBoxFirstOrderStatistics)
        FeatureExtraction.setTabOrder(self.checkBoxFirstOrderStatistics, self.checkBoxShapeBased2D)
        FeatureExtraction.setTabOrder(self.checkBoxShapeBased2D, self.checkBoxGLCM)
        FeatureExtraction.setTabOrder(self.checkBoxGLCM, self.checkBoxGLRLM)
        FeatureExtraction.setTabOrder(self.checkBoxGLRLM, self.checkBoxGLSZM)
        FeatureExtraction.setTabOrder(self.checkBoxGLSZM, self.checkBoxGLDM)
        FeatureExtraction.setTabOrder(self.checkBoxGLDM, self.checkBoxNGTDM)
        FeatureExtraction.setTabOrder(self.checkBoxNGTDM, self.plainTextOutput)
        FeatureExtraction.setTabOrder(self.plainTextOutput, self.buttonRun)

    def retranslateUi(self, FeatureExtraction):
        _translate = QtCore.QCoreApplication.translate
        FeatureExtraction.setWindowTitle(_translate("FeatureExtraction", "Feature Extraction"))
        self.labelSource.setText(_translate("FeatureExtraction", "Source Folder: "))
        self.buttonBrowseSourceFolder.setText(_translate("FeatureExtraction", "Browse..."))
        self.labelImageFilePatterns.setText(_translate("FeatureExtraction", "File Patterns (comma for separate)"))
        self.labelImageFilePatterns_2.setText(_translate("FeatureExtraction", "Include key:"))
        self.labelImageFilePatterns_4.setText(_translate("FeatureExtraction", "Show Name:"))
        self.labelImageFilePatterns_3.setText(_translate("FeatureExtraction", "Exclude key:"))
        self.radioImagePattern.setText(_translate("FeatureExtraction", "Image Pattern"))
        self.radioRoiPattern.setText(_translate("FeatureExtraction", "ROI Pattern"))
        self.buttonAddOne.setText(_translate("FeatureExtraction", "Add\n"
"One"))
        self.buttonRemoveOne.setText(_translate("FeatureExtraction", "Remove\n"
"One"))
        self.labelSource_2.setText(_translate("FeatureExtraction", "Feature Types"))
        self.label_2.setText(_translate("FeatureExtraction", "Image Types"))
        self.checkBoxOriginal.setText(_translate("FeatureExtraction", "Original"))
        self.checkBoxWavelet.setText(_translate("FeatureExtraction", "Wavelet Transform"))
        self.checkBoxSquare.setText(_translate("FeatureExtraction", "Square"))
        self.checkBoxSquareRoot.setText(_translate("FeatureExtraction", "Square Root"))
        self.checkBoxLoG.setText(_translate("FeatureExtraction", "Laplacian of Gaussian"))
        self.checkBoxLogarithm.setText(_translate("FeatureExtraction", "Logarithm"))
        self.checkBoxExponential.setText(_translate("FeatureExtraction", "Exponential"))
        self.checkBoxGradient.setText(_translate("FeatureExtraction", "Gradient"))
        self.checkBoxLocalBinaryPattern2D.setText(_translate("FeatureExtraction", "Local Binary Pattern (2D)"))
        self.checkBoxLocalBinaryPattern3D.setText(_translate("FeatureExtraction", "Local Binary Pattern (3D)"))
        self.label_3.setText(_translate("FeatureExtraction", "Feature Categories"))
        self.checkBoxFirstOrderStatistics.setText(_translate("FeatureExtraction", "First Order Statistics"))
        self.checkBoxShapeBased2D.setText(_translate("FeatureExtraction", "Shape-based"))
        self.checkBoxGLCM.setToolTip(_translate("FeatureExtraction", "Gray Level Cooccurence Matrix"))
        self.checkBoxGLCM.setText(_translate("FeatureExtraction", "GLCM"))
        self.checkBoxGLRLM.setToolTip(_translate("FeatureExtraction", "Gray Level Run Length Matrix"))
        self.checkBoxGLRLM.setText(_translate("FeatureExtraction", "GLRLM"))
        self.checkBoxGLSZM.setToolTip(_translate("FeatureExtraction", "Gray Level Size Zone Matrix"))
        self.checkBoxGLSZM.setText(_translate("FeatureExtraction", "GLSZM"))
        self.checkBoxGLDM.setToolTip(_translate("FeatureExtraction", "Gray Level Dependence Matrix"))
        self.checkBoxGLDM.setText(_translate("FeatureExtraction", "GLDM"))
        self.checkBoxNGTDM.setToolTip(_translate("FeatureExtraction", "Neigboring Gray Tone Difference Matrix"))
        self.checkBoxNGTDM.setText(_translate("FeatureExtraction", "NGTDM"))
        self.buttonRun.setText(_translate("FeatureExtraction", "Run"))

