# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\MyCode\FeatureAnalysisPro\GUI\Prepare.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Prepare(object):
    def setupUi(self, Prepare):
        Prepare.setObjectName("Prepare")
        Prepare.resize(1069, 697)
        self.gridLayout_4 = QtWidgets.QGridLayout(Prepare)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.buttonLoad = QtWidgets.QPushButton(Prepare)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonLoad.sizePolicy().hasHeightForWidth())
        self.buttonLoad.setSizePolicy(sizePolicy)
        self.buttonLoad.setMinimumSize(QtCore.QSize(0, 0))
        self.buttonLoad.setObjectName("buttonLoad")
        self.verticalLayout.addWidget(self.buttonLoad)
        self.textInformation = QtWidgets.QTextEdit(Prepare)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textInformation.sizePolicy().hasHeightForWidth())
        self.textInformation.setSizePolicy(sizePolicy)
        self.textInformation.setMinimumSize(QtCore.QSize(0, 300))
        self.textInformation.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.textInformation.setFont(font)
        self.textInformation.setObjectName("textInformation")
        self.verticalLayout.addWidget(self.textInformation)
        self.groupRemoveNonvalidValue = QtWidgets.QGroupBox(Prepare)
        self.groupRemoveNonvalidValue.setMinimumSize(QtCore.QSize(200, 0))
        self.groupRemoveNonvalidValue.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupRemoveNonvalidValue.setObjectName("groupRemoveNonvalidValue")
        self.gridLayout = QtWidgets.QGridLayout(self.groupRemoveNonvalidValue)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioRemoveNonvalidCases = QtWidgets.QRadioButton(self.groupRemoveNonvalidValue)
        self.radioRemoveNonvalidCases.setEnabled(False)
        self.radioRemoveNonvalidCases.setObjectName("radioRemoveNonvalidCases")
        self.verticalLayout_2.addWidget(self.radioRemoveNonvalidCases)
        self.radioRemoveNonvalidFeatures = QtWidgets.QRadioButton(self.groupRemoveNonvalidValue)
        self.radioRemoveNonvalidFeatures.setEnabled(False)
        self.radioRemoveNonvalidFeatures.setObjectName("radioRemoveNonvalidFeatures")
        self.verticalLayout_2.addWidget(self.radioRemoveNonvalidFeatures)
        self.buttonRemove = QtWidgets.QPushButton(self.groupRemoveNonvalidValue)
        self.buttonRemove.setEnabled(False)
        self.buttonRemove.setObjectName("buttonRemove")
        self.verticalLayout_2.addWidget(self.buttonRemove)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupRemoveNonvalidValue)
        self.groupSeparate = QtWidgets.QGroupBox(Prepare)
        self.groupSeparate.setObjectName("groupSeparate")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupSeparate)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radioSplitRandom = QtWidgets.QRadioButton(self.groupSeparate)
        self.radioSplitRandom.setEnabled(False)
        self.radioSplitRandom.setObjectName("radioSplitRandom")
        self.gridLayout_2.addWidget(self.radioSplitRandom, 0, 0, 1, 1)
        self.radioSplitRef = QtWidgets.QRadioButton(self.groupSeparate)
        self.radioSplitRef.setEnabled(False)
        self.radioSplitRef.setObjectName("radioSplitRef")
        self.gridLayout_2.addWidget(self.radioSplitRef, 0, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupSeparate)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.spinBoxSeparate = QtWidgets.QDoubleSpinBox(self.groupSeparate)
        self.spinBoxSeparate.setEnabled(False)
        self.spinBoxSeparate.setDecimals(1)
        self.spinBoxSeparate.setMaximum(1.0)
        self.spinBoxSeparate.setSingleStep(0.1)
        self.spinBoxSeparate.setProperty("value", 0.3)
        self.spinBoxSeparate.setObjectName("spinBoxSeparate")
        self.horizontalLayout_2.addWidget(self.spinBoxSeparate)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.checkUseClinicRef = QtWidgets.QCheckBox(self.groupSeparate)
        self.checkUseClinicRef.setEnabled(False)
        self.checkUseClinicRef.setObjectName("checkUseClinicRef")
        self.verticalLayout_3.addWidget(self.checkUseClinicRef)
        self.loadClinicRef = QtWidgets.QPushButton(self.groupSeparate)
        self.loadClinicRef.setEnabled(False)
        self.loadClinicRef.setObjectName("loadClinicRef")
        self.verticalLayout_3.addWidget(self.loadClinicRef)
        self.clearClinicRef = QtWidgets.QPushButton(self.groupSeparate)
        self.clearClinicRef.setEnabled(False)
        self.clearClinicRef.setObjectName("clearClinicRef")
        self.verticalLayout_3.addWidget(self.clearClinicRef)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.groupSeparate)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.loadTestingReference = QtWidgets.QPushButton(self.splitter)
        self.loadTestingReference.setEnabled(False)
        self.loadTestingReference.setObjectName("loadTestingReference")
        self.clearTestingReference = QtWidgets.QPushButton(self.splitter)
        self.clearTestingReference.setEnabled(False)
        self.clearTestingReference.setObjectName("clearTestingReference")
        self.gridLayout_2.addWidget(self.splitter, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupSeparate)
        self.buttonSave = QtWidgets.QPushButton(Prepare)
        self.buttonSave.setEnabled(False)
        self.buttonSave.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.buttonSave.setFont(font)
        self.buttonSave.setObjectName("buttonSave")
        self.verticalLayout.addWidget(self.buttonSave)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.tableFeature = QtWidgets.QTableWidget(Prepare)
        self.tableFeature.setMinimumSize(QtCore.QSize(600, 0))
        self.tableFeature.setObjectName("tableFeature")
        self.tableFeature.setColumnCount(0)
        self.tableFeature.setRowCount(0)
        self.horizontalLayout.addWidget(self.tableFeature)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(Prepare)
        QtCore.QMetaObject.connectSlotsByName(Prepare)

    def retranslateUi(self, Prepare):
        _translate = QtCore.QCoreApplication.translate
        Prepare.setWindowTitle(_translate("Prepare", "Data Preparation"))
        self.buttonLoad.setText(_translate("Prepare", "Load Feature Matrix"))
        self.groupRemoveNonvalidValue.setTitle(_translate("Prepare", "Remove non-valid value"))
        self.radioRemoveNonvalidCases.setText(_translate("Prepare", "Remove non-valid Cases"))
        self.radioRemoveNonvalidFeatures.setText(_translate("Prepare", "Remove non-valid Features"))
        self.buttonRemove.setText(_translate("Prepare", "Remove"))
        self.groupSeparate.setTitle(_translate("Prepare", "Split into Train and Test"))
        self.radioSplitRandom.setText(_translate("Prepare", "Random"))
        self.radioSplitRef.setText(_translate("Prepare", "Testing Ref"))
        self.label.setText(_translate("Prepare", "Test Percent"))
        self.checkUseClinicRef.setText(_translate("Prepare", "Clinic Ref"))
        self.loadClinicRef.setText(_translate("Prepare", "Load Clinic Ref"))
        self.clearClinicRef.setText(_translate("Prepare", "Clear Clinic Ref"))
        self.loadTestingReference.setText(_translate("Prepare", "Load Testing Ref"))
        self.clearTestingReference.setText(_translate("Prepare", "Clear Testing Ref"))
        self.buttonSave.setText(_translate("Prepare", "Check and Save"))

