# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Prepare.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Prepare(object):
    def setupUi(self, Prepare):
        Prepare.setObjectName("Prepare")
        Prepare.resize(1025, 820)
        self.totalLayout = QtWidgets.QGridLayout(Prepare)
        self.totalLayout.setObjectName("totalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.FeatureExtractionButton = QtWidgets.QPushButton(Prepare)
        self.FeatureExtractionButton.setObjectName("FeatureExtractionButton")
        self.verticalLayout.addWidget(self.FeatureExtractionButton)
        self.buttonLoad = QtWidgets.QPushButton(Prepare)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonLoad.sizePolicy().hasHeightForWidth())
        self.buttonLoad.setSizePolicy(sizePolicy)
        self.buttonLoad.setMinimumSize(QtCore.QSize(0, 0))
        self.buttonLoad.setObjectName("buttonLoad")
        self.verticalLayout.addWidget(self.buttonLoad)
        self.textInformation = QtWidgets.QTextEdit(Prepare)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textInformation.sizePolicy().hasHeightForWidth())
        self.textInformation.setSizePolicy(sizePolicy)
        self.textInformation.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.textInformation.setFont(font)
        self.textInformation.setObjectName("textInformation")
        self.verticalLayout.addWidget(self.textInformation)
        self.groupRemoveNonvalidValue = QtWidgets.QGroupBox(Prepare)
        self.groupRemoveNonvalidValue.setMinimumSize(QtCore.QSize(200, 0))
        self.groupRemoveNonvalidValue.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupRemoveNonvalidValue.setObjectName("groupRemoveNonvalidValue")
        self.gridLayout = QtWidgets.QGridLayout(self.groupRemoveNonvalidValue)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioRemoveNonvalidCases = QtWidgets.QRadioButton(self.groupRemoveNonvalidValue)
        self.radioRemoveNonvalidCases.setObjectName("radioRemoveNonvalidCases")
        self.verticalLayout_2.addWidget(self.radioRemoveNonvalidCases)
        self.radioRemoveNonvalidFeatures = QtWidgets.QRadioButton(self.groupRemoveNonvalidValue)
        self.radioRemoveNonvalidFeatures.setObjectName("radioRemoveNonvalidFeatures")
        self.verticalLayout_2.addWidget(self.radioRemoveNonvalidFeatures)
        self.buttonRemove = QtWidgets.QPushButton(self.groupRemoveNonvalidValue)
        self.buttonRemove.setEnabled(False)
        self.buttonRemove.setObjectName("buttonRemove")
        self.verticalLayout_2.addWidget(self.buttonRemove)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupRemoveNonvalidValue)
        self.groupSeparate = QtWidgets.QGroupBox(Prepare)
        self.groupSeparate.setObjectName("groupSeparate")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupSeparate)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.groupSeparate)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.loadTestingReference = QtWidgets.QPushButton(self.groupSeparate)
        self.loadTestingReference.setObjectName("loadTestingReference")
        self.verticalLayout_3.addWidget(self.loadTestingReference)
        self.clearTestingReference = QtWidgets.QPushButton(self.groupSeparate)
        self.clearTestingReference.setObjectName("clearTestingReference")
        self.verticalLayout_3.addWidget(self.clearTestingReference)
        self.spinBoxSeparate = QtWidgets.QDoubleSpinBox(self.groupSeparate)
        self.spinBoxSeparate.setDecimals(1)
        self.spinBoxSeparate.setMaximum(1.0)
        self.spinBoxSeparate.setSingleStep(0.1)
        self.spinBoxSeparate.setProperty("value", 0.3)
        self.spinBoxSeparate.setObjectName("spinBoxSeparate")
        self.verticalLayout_3.addWidget(self.spinBoxSeparate)
        self.checkSeparate = QtWidgets.QCheckBox(self.groupSeparate)
        self.checkSeparate.setTristate(False)
        self.checkSeparate.setObjectName("checkSeparate")
        self.verticalLayout_3.addWidget(self.checkSeparate)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupSeparate)
        self.groupBox_3 = QtWidgets.QGroupBox(Prepare)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radioNoneBalance = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioNoneBalance.setChecked(True)
        self.radioNoneBalance.setObjectName("radioNoneBalance")
        self.verticalLayout_4.addWidget(self.radioNoneBalance)
        self.radioUpSampling = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioUpSampling.setObjectName("radioUpSampling")
        self.verticalLayout_4.addWidget(self.radioUpSampling)
        self.radioDownSampling = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioDownSampling.setObjectName("radioDownSampling")
        self.verticalLayout_4.addWidget(self.radioDownSampling)
        self.radioSmote = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioSmote.setObjectName("radioSmote")
        self.verticalLayout_4.addWidget(self.radioSmote)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.buttonSave = QtWidgets.QPushButton(Prepare)
        self.buttonSave.setEnabled(False)
        self.buttonSave.setObjectName("buttonSave")
        self.verticalLayout.addWidget(self.buttonSave)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.tableFeature = QtWidgets.QTableWidget(Prepare)
        self.tableFeature.setObjectName("tableFeature")
        self.tableFeature.setColumnCount(0)
        self.tableFeature.setRowCount(0)
        self.horizontalLayout.addWidget(self.tableFeature)
        self.totalLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(Prepare)
        QtCore.QMetaObject.connectSlotsByName(Prepare)

    def retranslateUi(self, Prepare):
        _translate = QtCore.QCoreApplication.translate
        Prepare.setWindowTitle(_translate("Prepare", "Form"))
        self.FeatureExtractionButton.setText(_translate("Prepare", "FeatureExtraction"))
        self.buttonLoad.setText(_translate("Prepare", "Load"))
        self.groupRemoveNonvalidValue.setTitle(_translate("Prepare", "Remove non-valid value"))
        self.radioRemoveNonvalidCases.setText(_translate("Prepare", "Remove non-valid Cases"))
        self.radioRemoveNonvalidFeatures.setText(_translate("Prepare", "Remove non-valid Features"))
        self.buttonRemove.setText(_translate("Prepare", "Remove"))
        self.groupSeparate.setTitle(_translate("Prepare", "Separate Train and Test"))
        self.label.setText(_translate("Prepare", "Percentage of Testing data"))
        self.loadTestingReference.setText(_translate("Prepare", "Load Testing Dataset"))
        self.clearTestingReference.setText(_translate("Prepare", "Clear Testing Dataset"))
        self.checkSeparate.setText(_translate("Prepare", "Separate Train And Test"))
        self.groupBox_3.setTitle(_translate("Prepare", "Balance Data"))
        self.radioNoneBalance.setText(_translate("Prepare", "None Balance"))
        self.radioUpSampling.setText(_translate("Prepare", "UpSampling"))
        self.radioDownSampling.setText(_translate("Prepare", "DownSampling"))
        self.radioSmote.setText(_translate("Prepare", "SMOTE"))
        self.buttonSave.setText(_translate("Prepare", "Check and Save"))


